version: "3.4"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8887:80"
    volumes:
      - ./nginx/default.conf.local:/etc/nginx/nginx.conf